[package]
name = "preprocess"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
libs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
testing-mode = ["libs/testing-mode"]
