[package]
name = "verify"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
icicle-runtime = { workspace = true }
icicle-core = { workspace = true }
icicle-hash = { workspace = true }
icicle-bls12-381 = { workspace = true }
libs = { workspace = true }
preprocess = { workspace = true }
prove = { workspace = true }
hex = { workspace = true }

[features]
default = []
testing-mode = []
