[package]
name = "trusted-setup"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
icicle-runtime = { workspace = true }
icicle-core = { workspace = true }
icicle-bls12-381 = { workspace = true }
libs = { workspace = true }
rayon = { workspace = true }
lazy_static = "1.5.0"
bincode = "1.3.3"
memmap2 = "0.9.5"

[features]
default = []
testing-mode = ["libs/testing-mode"]
