[package]
name = "mpc-setup"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
icicle-core = { workspace = true }
icicle-bls12-381 = { workspace = true }
icicle-runtime = { workspace = true }

libs = { workspace = true }
rayon = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-serialize = "0.5.0"
 rand = "0.8.5"
blake2 = "0.8.1"
rand_chacha = "0.3.1"
bincode = "1.3.3"
memmap = "0.7.0"
generic-array = "0.14.7"
typenum = "1.18.0"
serde_json = "1.0.140"
digest = "0.10.7"
hex = "0.4.3"
ark-poly = "0.3"
ark-std = "0.3"
lazy_static = "1.5.0"
num_cpus = "1.16.0"
num-bigint = "0.4.6"
blake3 = "1.8.2"
clap = { version = "4.4", features = ["derive"] }
[features]
default = []
testing-mode = ["libs/testing-mode"]


