[package]
name = "prove"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
icicle-runtime = { workspace = true }
icicle-core = { workspace = true }
icicle-bls12-381 = { workspace = true }
libs = { workspace = true }
tiny-keccak = "1.5"

[features]
default = []
testing-mode = []
