name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      # Setup Rust
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Setup Foundry
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Build
      - name: Build all packages
        run: make build

      # Test
      - name: Test all packages
        run: make test
